### PR TITLE
Feature/update operation

### PR DESCRIPTION
**Pull request by eqinox76**
Hey sergio,

i had a issue where the update/patch operation was needed as a command line utility for firestore. So i implemented it in fuego. Which has been really easy. Thereafter i decided to invest some more time and add unit tests and some documentation.

If you think this feature may be useful for others feel free to merge it. If not feel also free to delete this branch.

Regards,
eqinox76

### CODE REVIEW

**Comment by sgarciac** [comment]
Hello Carsten. Great. looks good to me! I'll merge. I'll create a new release soon.

**Comment by eqinox76** [comment]
Great and thanks for the fast reply!
Sadly i added a bug which prevented the update operation to work with anything deeper than 1 level...
Fixed, added a unit test and pushed the fix to this branch.

Regards,
eqinox76

**Comment by sgarciac** [comment]
No problem. One small thing: I think it would be better to build a FieldPath instead of concatenating a string to build the Update.

**Comment by sgarciac** [comment]
ohhhh, on a second look, if I'm not wrong, what the command is doing could more simply be achieved by calling Set with the MergeAll option instead of Update.

**Comment by eqinox76** [comment]
Well spotted. This comment confuses me somewhat:
```golang
// MergeAll is a SetOption that causes all the field paths given in the data argument
// to Set to be overwritten. It is not supported for struct data.
var MergeAll SetOption = merge{all: true}
```
It is not supported for struct data.
But a fast test shows that it is indeed working fine with the test cases.

So i think it makes much more sense to add a --merge flag to the set command than adding an update command?

**Comment by sgarciac** [comment]
Yep, I had a bit of a hard time understading that part but I finally got that it's strictly about go-lang's Structs, as in their example. This is of no concern for us since of all our data is map[string]interface{}.

Yep, I agree that the more natural way would be to add a flag to the set command.

**Comment by eqinox76** [comment]
Done. Added a --merge flag. That saves nearly all my code so well spotted!
I adjusted the documentation and the unit tests. Let me know if something else is missing.

Regards,
eqinox76

**Pull request merged**
