### PR TITLE
Feat/support copying 

### PR DESCRIPTION
**Pull request by leitc**
Support copying documents and collection.
Previously, we needed to first download the document or collection and then upload the documents to implement copying. 
Now we can just specify two different paths.

### CODE REVIEW

**Comment by sgarciac** [comment]
Thanks @leitc! I'll try to have a look at it this weekend.

**Comment by sgarciac** [comment]
Hello, @leitc I had a look at your PR, and I think two things warrant a deeper look: 1) I think it is likely you can hit the same problem that @eqinox76 had with big collections and described here https://github.com/sgarciac/fuego/pull/3#issue-278280801 , that is, timeouts. We'll probably want to paginate, as with the query command. 2) I only had a quick look at the code, but Im worried launching too many goroutines might hit golangs http connection pool limit quickly?

**Comment by leitc** [comment]
Hi, @sgarciac, sorry for the delay.  

For the first question, I don't think there will be a timeout issue, because I use `DocumentRefs` api to build an iterator based on the collection then fetch document piece by piece rather than fetch all documents in bulk. In my case, I tried to copy a collection with 20,000 pieces of documents, and it works well.

For the second question, I think you're right when the big collections have a very deep hierarchy. But in normal cases, I think it will work well. In my case, I tried to count the number of goroutines when copying a collection with 20,000 pieces of documents with sub collection, the number of goroutines stabilized at around 300. But uncontrolled numbers of goroutines are indeed not graceful.

I'm going to find a more graceful way to control the number of the goroutines this weekend.

**Comment by sgarciac** [comment]
@leitc great, I think you are right. I'll have a look at the query implementation, we are now using an iterator and batching might no longer be needed, thanks :+1: 

A minor nitpick also is that the client creation functions could use some refactoring to eliminate the duplicated code.

**Comment by sgarciac** [comment]
@leitc : I will merge your PR this week, just let me know if you still want to make some changes.

**Comment by leitc** [comment]
hi, @sgarciac , I've updated the code.

**Comment by sgarciac** [comment]
Great stuff, @leitc , merged. Thanks.

**Pull request merged**
