### PR TITLE
Feature/query batch parameter

### PR DESCRIPTION
**Pull request by eqinox76**
Hey Sergio,

thanks for pointing out your unit tests. I added some more for the batch parameter and fixed the revealed bugs.

From my perspective the batch parameter is working now and it seems to not break anything. The code gets a bit more complicated by the batching itself and some firestore api requirements (needs ordering when using startAt for later batching).

As discussed the batch parameter is very useful for my use case. But if you feel that the added complexity is too much feel free to decline the pull request. 

Regards,
Carsten

### CODE REVIEW

**Comment by sgarciac** [comment]
Hi Carsten, thanks again for the PR.
would you mind testing this branch: https://github.com/sgarciac/fuego/commits/batchs to see if it solves the timing-out issue you had on big collections? (that's how iterating over the query results should have been done from the beggining, sorry about that 😓). 

If it doesnt work, I'm willing to add the batch option, and I will look into the details of your PR later. At a first glance, I don't like having the client add orderby parameters to make the batching work. what would you think of letting the user set those by hand if he wants/needs batching?

**Comment by eqinox76** [comment]
Hmm sadly that is also running into a timeout. Would not have expected that from the docu. Here is a bit printf logging:
```
$ ./fuego q --limit 300000 testcollection
2019/05/31 09:46:33 Starting query
2019/05/31 09:46:37 10000 items received
2019/05/31 09:46:41 20000 items received
2019/05/31 09:46:44 30000 items received
2019/05/31 09:46:49 40000 items received
2019/05/31 09:46:52 50000 items received
2019/05/31 09:46:56 60000 items received
2019/05/31 09:47:00 70000 items received
2019/05/31 09:47:04 80000 items received
2019/05/31 09:47:07 90000 items received
2019/05/31 09:47:11 100000 items received
2019/05/31 09:47:15 110000 items received
2019/05/31 09:47:19 120000 items received
2019/05/31 09:47:22 130000 items received
2019/05/31 09:47:26 140000 items received
2019/05/31 09:47:30 150000 items received
2019/05/31 09:47:33 Query failed at  158400 items
Failed to list documents. 
rpc error: code = DeadlineExceeded desc = The datastore operation timed out, or the data was temporarily unavailable.
exit status 86

Anyway using the iterator interface is most likely better for the memory footprint and you could also think about putting the serialization to json into a go routine.

Coming back to the batch option. I acknowledge that this makes the query.go file much more complicated. Especially with the ordering defaults and stuff.
Would it make more sense to have a higher level function which uses the queryCommandAction as is? That would keep the query command as near as possible to the client lib while offering a way to get bigger batches via fuego?

**Comment by sgarciac** [comment]
Hello Carsten.

It seems indeed that there is no way to guarantee firestore won't timeout when querying big collections without paginating ourselves. We could play with this: https://github.com/firebase/firebase-admin-node/issues/349#issuecomment-467311110 , but it's not a real solution. So, let's merge this! Let's keep it in the query command, we can always refactor the code to make it clearer.

I think however, unless I'm understanding the documentation wrong, that there is really no need to set default orderby values ourselves. The go client does it already, when a document is passed as a startAt:  https://github.com/googleapis/google-cloud-go/blob/5ea6847e42e62cd77aab6fb7047b15132174a634/firestore/query.go#L322, following these rules: https://cloud.google.com/firestore/docs/reference/rest/v1/StructuredQuery (see the orderby part). 

As long as we always use a document as the parameter for startAt, we should be ok. I tested this, removing from your code the part that sets a default orderby, and always calling ```query = query.StartAfter(last)``` during the batching (instead of passing the documentId field when no orderby-s where defined), and it passed your tests.

**Comment by sgarciac** [comment]
Hi carsten, I merged your PR into the branch feature/batched-query and added you as a collaborator. Lets keep working on that branch. I removed the default orderby code, and tests are still working. Let me know what you think about this. We still need to use the iterator interface as in my example.

**Pull request merged**
